version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2015
notifications:
- provider: Email
  to:
  - ianeporter88@gmail.com
  subject: vtkmofo build AppVeyor
  message: AppVeyor has re-built vtkmofo due to pull request
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
